### ISSUE TITLE
Setting admin override when testing localhost

### ISSUE THREAD

**Issue by getcontrol** [norestlabs/mousekyc-admin#4]
The README instructions state : 
_#### Logging In
You can **set an application owner email the configuration of the backend**. That user will be able to login without approving each other administrator that uses the application. Set this to whichever email you would like to use for login, then get started!_

Which module and what file is that set in exactly ? Thanks!

**Comment by gedanziger** [comment]
Hey, 

You can set it in this file of the backend module:

https://github.com/norestlabs/mousekyc-be/blob/master/src/config/default.js

You can configure an email provider, email return address, and default admin address.

**Comment by getcontrol** [comment]
I really want to get this going , but keeping getting stuck on this application owner email issue. 

I have changed config/default.js  masterEmail from  'galen@norestlabs.com' to my own personal email. 

When I go to Admin login and use  my own personal email, the screen remains on Pending and just lags. Signing up with same email on FE doesn't produce any results and signing in with same email produced "Not verified user !"

**Comment by oleg-baturov** [comment]
@getcontrol Admin is special scenario in this project.
If you manage user, then signup & login is the same as other service.
If you signup user, it is created with `verified=false`. And send mail to master owner that someone tried to register admin.
Only master owner can approve the new admin.
Once master owner approved the admin, he can play the role as admin.
Unless, his admin account is still not verified.

`I have changed config/default.js masterEmail from 'galen@norestlabs.com' to my own personal email.`
It means, your mail is master owner.

**Comment by oleg-baturov** [comment]
@getcontrol And you need to check mailgun config keys.
Without correct key config, mail feature will not work.

**Comment by oleg-baturov** [comment]
I will close this issue ticket now.
