### ISSUE TITLE
admin user signup error

### ISSUE THREAD

**Issue by oleg-baturov** [norestlabs/mousekyc-admin#7]
When filling `email` and `password` in signup screen, it sends signup request to the server instead of validation.
We need to fix it, so admin frontend sends `request` on `signup` button click.

![image](https://user-images.githubusercontent.com/32242962/49210985-2f95d900-f40a-11e8-869f-b27786f09aad.png)

**Comment by rutkat** [comment]
Signup is still broken. Submitting form sends the data to `https://mousekyc-server.mousebelt.com/admin/signup` POST 200 status and nothing else happens. Then when trying to login with the given email address, an error appears "User is not verified!"

**Comment by oleg-baturov** [comment]
if it is admin signup, you should set `verified` to true in server db.

**Comment by oleg-baturov** [comment]
Fixed by 8f27dc0e277d582db753c30728c0f370cd05ff7a
