### ISSUE TITLE
user/gentoken 

### ISSUE THREAD

**Issue by getcontrol** [norestlabs/mousekyc-admin#8]
When logging into admin with masterEmail (set in mousekyc-be/src/config/default.js) + API pointing to localhost , I keep getting a 404 error :

bundle.js:183518 POST http://localhost:3006//user/gentoken 404 (Not Found)

I reviewed my code and can't find an extra slash in it.

**Comment by getcontrol** [comment]
NM I found the extra problem slash in services/constants.js :+1: 
export const apiEndpoint = 'http://localhost:3006/';

For local config should this be : 
_a. export const apiEndpoint = 'http://localhost:3000';
b. export const apiEndpoint = 'http://localhost:3001'; (sign up /sign in)
c. export const apiEndpoint = 'http://localhost:3006'; (admin login)_
?

**Comment by oleg-baturov** [comment]
good, closing this issue now.
